spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.106.75.5:3306/blog?useSSL=false&useUnicode=true&characterEncoding=utf8
    username: root
    password: Llny4000755
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

logging:
  level:
    root: info
    com.lrm: debug
  file: log/blog-dev.log



